#pragma once
#define _CRT_SECURE_NO_WARNINGS
#define _SCL_SECURE_NO_WARNINGS
#pragma execution_character_set("utf-8")
#pragma warning(disable:4010)
#pragma warning(disable:4244)
#pragma warning(disable : 4996) 
#include <Windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#include <assert.h>
#include <stdint.h>
#include <vector>
#include <algorithm>
#include <process.h>
#include <typeinfo>
#include <iostream>
#include <fstream>
#include <sstream> 
#include <string>
#include <time.h>
#include <d3d9.h>
#include <d3dx9.h>
#include <d3dx9core.h>
#pragma comment (lib, "d3dx9.lib")
#include <intrin.h>
#include <memory>
#include <exception>
#include <unordered_map>
#include <inttypes.h>
#include <Winuser.h>
#include <comdef.h> 
#include <map>
#include <algorithm>
#include <cstdint>
#include <iomanip>
#include <random>
#include <locale>
#include <codecvt>
#include <cstdint>  
#include <immintrin.h>
#include <functional>
#include <mutex>
#include <winternl.h>
#include "hde\hde.h"
#pragma comment(lib,"hde.lib") 
#include "memcpy_fast.h"